# DOCKERFILE FOR LINUX LECTURES ------------------------------------------------
# The following is the Dockerfile for use in teaching the fundamentals of Linux
# and ROS. The code is originally based by the user tiryoh with their link
#
# https://github.com/Tiryoh/docker-ros2-desktop-vnc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# This Dockerfile is based on https://github.com/AtsushiSaito/docker-ubuntu-sweb
# which is released under the Apache-2.0 license.
#
# INSTALLATION INSTRUCTIONS
#
# To install please copy this Dockerfile and its accompanying entrypoint.sh
# into the SAME directory i.e., Docker/Dockerfile and Docker/entrypoint.sh
# using a terminal move into this directory and run the following command.
#
# docker build . -t mci:ros2 -f Dockerfile
#
# NOTE: This operation may take 15-20 mins.
#
# Once installation is done, plese open your browser and type:
# 127.0.0.1:6080
#

# Declare the ubuntu version
FROM ubuntu:jammy-20250404

# Define the target-platform and the current maintainer
ARG TARGETPLATFORM
LABEL maintainer="dtm@mci4me.at"

# Execute the following command as string
SHELL ["/bin/bash", "-c"]

# Upgrade Ubuntu Jammy and remove downloaded list of packages
RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y && \
    apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# Install Ubuntu Mate desktop and remove downloaded list of packages
RUN apt-get update -q && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        ubuntu-mate-desktop && \
    apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# Add important packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        tigervnc-standalone-server tigervnc-common \
        supervisor wget curl gosu git sudo python3-pip tini nano\
        build-essential vim sudo lsb-release locales info\
        bash-completion tzdata emacs \
        dos2unix && \ 
    apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# Install noVNC and Websockify
RUN git clone \
    https://github.com/AtsushiSaito/noVNC.git \
    -b add_clipboard_support /usr/lib/novnc

RUN pip install git+https://github.com/novnc/websockify.git@v0.10.0
RUN ln -s /usr/lib/novnc/vnc.html /usr/lib/novnc/index.html

# Set remote resize function enabled by default
RUN sed -i \
    "s/UI.initSetting('resize', 'off');/UI.initSetting('resize', 'remote');/g" \
    /usr/lib/novnc/app/ui.js

# Disable auto update and crash report
RUN sed -i 's/Prompt=.*/Prompt=never/' /etc/update-manager/release-upgrades
RUN sed -i 's/enabled=1/enabled=0/g' /etc/default/apport

# Install Firefox and its configuration
RUN DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:mozillateam/ppa -y && \
    echo 'Package: *' > /etc/apt/preferences.d/mozilla-firefox && \
    echo 'Pin: release o=LP-PPA-mozillateam' \
    >> /etc/apt/preferences.d/mozilla-firefox && \
    echo 'Pin-Priority: 1001' >> /etc/apt/preferences.d/mozilla-firefox && \
    apt-get update -q && \
    apt-get install -y \
    firefox && \
    apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# Install VSCodium for people who are accosstomed to VSCode but
# prefer to keep it open-source
RUN wget https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
    -O /usr/share/keyrings/vscodium-archive-keyring.asc && \
    echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.asc ] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main' \
    | tee /etc/apt/sources.list.d/vscodium.list && \
    apt-get update -q && \
    apt-get install -y codium && \
    apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*

# Install ROS Humble version
ENV ROS_DISTRO=humble

# Install Desktop version
ARG INSTALL_PACKAGE=desktop

RUN apt-get update -q && \
    apt-get install -y curl gnupg2 lsb-release && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    apt-get update -q && \
    apt-get install -y ros-${ROS_DISTRO}-${INSTALL_PACKAGE} \
    python3-argcomplete \
    python3-colcon-common-extensions \
    python3-rosdep python3-vcstool && \
    rosdep init && \
    rm -rf /var/lib/apt/lists/*

RUN rosdep update

# Install simulation package only on amd64
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    apt-get update -q && \
    apt-get install -y \
    ros-${ROS_DISTRO}-gazebo-ros-pkgs \
    ros-${ROS_DISTRO}-ros-ign && \
    rm -rf /var/lib/apt/lists/*; \
    fi

# Download the Linux Tutorial file from repo
ARG ZIPFILE="https://github.com/dTmC0945/L-MCI-BSc-Mobile-Robotics/raw/refs/heads/main/datasets/linux-tutorials.zip"

# Create some user directories to simulate a desktop environment
RUN mkdir -p \
    /home/ubuntu/Downloads \
    /home/ubuntu/Downloads \
    /home/ubuntu/Desktop

# Download the tutorial files to their correct place
RUN cd "/home/ubuntu/Desktop" && \
    wget -O "linux.zip" "$ZIPFILE" && \
    unzip "linux.zip" && \
    rm "linux.zip"

# Enable apt-get completion after running `apt-get update` in the container
RUN rm /etc/apt/apt.conf.d/docker-clean

# Copy the entrypoint.sh into the image
COPY ./entrypoint.sh /

# Convert file for linux compatability
RUN dos2unix /entrypoint.sh
ENTRYPOINT [ "/bin/bash", "-c", "/entrypoint.sh" ]

# Define user and password
ENV USER=ubuntu
ENV PASSWD=ubuntu
